# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Serial Scripter Deployment

env:
  PYTHON_VERSION: '3.9'               # set this to the Python version to use

#on:
#  push:
#    branches:
#      - main
      
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python version
        uses: actions/setup-python@v4

        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Set up dependency caching for faster installs
        uses: actions/cache@v3

        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install -r /home/runner/work/SerialScripter/SerialScripter/SerialScripter/requirements.txt
        
#      - name: Run webserver
#        working-directory: /home/runner/work/SerialScripter/SerialScripter/SerialScripter/
#        timeout-minutes: 1
#        run: python3 ./main.py

      # Optional: Add a step to run tests here (PyTest, Django test suites, etc.)

      - name: Deploy
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_PROD }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST_PROD }}
          REMOTE_USER: ${{ secrets.REMOTE_USER_PROD }}
          TARGET: /home/ubuntu/webserver_main
